In [1]:
import os
import pandas as pd
from datetime import date

In [25]:
data= pd.read_csv('Ordenes_productos_C1_M2_Raw.csv', sep=';',encoding='latin-1')

data.head()

,orden_id,order_item_id,producto_id,vendedor_id,fecha_envio_limite,precio,valor_flete,codigo_postal_vendedor,ciudad_vendedor,departamento_vendedor,nombre_categoria_producto,longitud_nombre_producto,longitud_descripcion_producto,cantidad_fotos_producto,peso_g_producto,longitud_cm_producto,altura_cm_producto,ancho_cm_producto
0,107500PO59A,A,PO59,VE5389,7/04/2018 18:12,271.86,30.72,52435,Mallama,Nariño,Productos ecoamigables,6.0,7.0,27.0,2486.0,17.0,11.0,14.0
1,37493PS22B,B,PS22,VE1558,20/10/2017 9:07,115.73,4.68,52203,Colon,Nariño,Carnicería,10.0,31.0,20.0,256.0,43.0,2.0,21.0
2,28050PK20B,B,PK20,VE9159,17/08/2017 8:15,432.99,82.70,66001,Pereira,Risaralda,Deportes,25.0,5.0,4.0,5270.0,9.0,27.0,29.0
3,52187PA10A,A,PA10,VE3159,23/09/2017 23:27,108.38,35.39,52435,Mallama,Nariño,Electrodomésticos,10.0,1.0,6.0,734.0,46.0,48.0,22.0
4,84639PR12A,A,PR12,VE5090,7/01/2018 11:50,51.50,11.10,73001,Ibague,Tolima,Frutas y verduras,23.0,16.0,35.0,884.0,45.0,26.0,18.0

In [3]:
# Revisar los tipos de datos del dataset
data.dtypes

orden_id                          object
order_item_id                     object
producto_id                       object
vendedor_id                       object
fecha_envio_limite                object
precio                           float64
valor_flete                      float64
codigo_postal_vendedor             int64
ciudad_vendedor                   object
departamento_vendedor             object
nombre_categoria_producto         object
longitud_nombre_producto         float64
longitud_descripcion_producto    float64
cantidad_fotos_producto          float64
peso_g_producto                  float64
longitud_cm_producto             float64
altura_cm_producto               float64
ancho_cm_producto                float64
dtype: object

In [4]:
# Obtener estadísticas básica
data['codigo_postal_vendedor'].describe()

count    10134.000000
mean     49991.684626
std      22463.895340
min       5001.000000
25%      50001.000000
50%      52323.000000
75%      54003.000000
max      99001.000000
Name: codigo_postal_vendedor, dtype: float64

In [5]:
# lo mejor es convertirlo en categórico
data['codigo_postal_vendedor']=data['codigo_postal_vendedor'].astype(str)
data.dtypes

orden_id                          object
order_item_id                     object
producto_id                       object
vendedor_id                       object
fecha_envio_limite                object
precio                           float64
valor_flete                      float64
codigo_postal_vendedor            object
ciudad_vendedor                   object
departamento_vendedor             object
nombre_categoria_producto         object
longitud_nombre_producto         float64
longitud_descripcion_producto    float64
cantidad_fotos_producto          float64
peso_g_producto                  float64
longitud_cm_producto             float64
altura_cm_producto               float64
ancho_cm_producto                float64
dtype: object

In [6]:
## Función para revisar nulos
data.isna().sum()/len(data)

orden_id                         0.00000
order_item_id                    0.00000
producto_id                      0.00000
vendedor_id                      0.00000
fecha_envio_limite               0.00000
precio                           0.00000
valor_flete                      0.00000
codigo_postal_vendedor           0.00000
ciudad_vendedor                  0.00000
departamento_vendedor            0.00000
nombre_categoria_producto        0.00227
longitud_nombre_producto         0.00227
longitud_descripcion_producto    0.00227
cantidad_fotos_producto          0.00227
peso_g_producto                  0.00227
longitud_cm_producto             0.00227
altura_cm_producto               0.00227
ancho_cm_producto                0.00227
dtype: float64

In [7]:
data.shape

(10134, 18)

In [8]:
# eliminar los datos vacío
data=data.dropna()
data.shape

(10111, 18)

In [9]:
#Revisar cuáles registros están duplicados
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
10129    False
10130    False
10131    False
10132    False
10133    False
Length: 10111, dtype: bool

In [10]:
# establecer un método para eliminar duplicados
data=data.drop_duplicates()
data.head(5)

,orden_id,order_item_id,producto_id,vendedor_id,fecha_envio_limite,precio,valor_flete,codigo_postal_vendedor,ciudad_vendedor,departamento_vendedor,nombre_categoria_producto,longitud_nombre_producto,longitud_descripcion_producto,cantidad_fotos_producto,peso_g_producto,longitud_cm_producto,altura_cm_producto,ancho_cm_producto
0,107500PO59A,A,PO59,VE5389,7/04/2018 18:12,271.86,30.72,52435,Mallama,Nariño,Productos ecoamigables,6.0,7.0,27.0,2486.0,17.0,11.0,14.0
1,37493PS22B,B,PS22,VE1558,20/10/2017 9:07,115.73,4.68,52203,Colon,Nariño,Carnicería,10.0,31.0,20.0,256.0,43.0,2.0,21.0
2,28050PK20B,B,PK20,VE9159,17/08/2017 8:15,432.99,82.70,66001,Pereira,Risaralda,Deportes,25.0,5.0,4.0,5270.0,9.0,27.0,29.0
3,52187PA10A,A,PA10,VE3159,23/09/2017 23:27,108.38,35.39,52435,Mallama,Nariño,Electrodomésticos,10.0,1.0,6.0,734.0,46.0,48.0,22.0
4,84639PR12A,A,PR12,VE5090,7/01/2018 11:50,51.50,11.10,73001,Ibague,Tolima,Frutas y verduras,23.0,16.0,35.0,884.0,45.0,26.0,18.0

In [11]:
#Mostrar la totalidad de datos duplicados, la función .sum() muestra la suma de registros
float(data.duplicated().sum())

0.0

In [12]:
## Arreglo de datos
hoy = pd.to_datetime("now")
hoy

Timestamp('2026-02-25 22:08:09.725109')

In [13]:
#restar los días que hay entre hoy y la fecha de pedido
data['fecha_envio_limite']

0         7/04/2018 18:12
1         20/10/2017 9:07
2         17/08/2017 8:15
3        23/09/2017 23:27
4         7/01/2018 11:50
               ...
10129     1/04/2018 11:38
10130    21/10/2017 17:09
10131     10/10/2017 8:37
10132     13/11/2017 3:20
10133    26/12/2017 19:34
Name: fecha_envio_limite, Length: 10111, dtype: object

In [14]:
data['fecha_envio_limite']-hoy

TypeError: unsupported operand type(s) for -: 'numpy.ndarray' and 'Timestamp'

In [15]:
# Revisar el tipo de dato que es la columnda de fechas
data[['fecha_envio_limite']].dtypes

fecha_envio_limite    object
dtype: object

In [22]:
data['fecha_envio_limite'] = pd.to_datetime(
    data['fecha_envio_limite'],
    format="%d/%m/%Y %H:%M",
    errors="raise"
)

In [23]:
# revisar que el tipo de dato es de fecha
data[['fecha_envio_limite']].dtypes

fecha_envio_limite    datetime64[ns]
dtype: object

In [24]:
# Hacer operaciones con el tipo de dato correcto
hoy-data['fecha_envio_limite']

0       2881 days 03:56:09.725109
1       3050 days 13:01:09.725109
2       3114 days 13:53:09.725109
3       3076 days 22:41:09.725109
4       2971 days 10:18:09.725109
                   ...
10129   2887 days 10:30:09.725109
10130   3049 days 04:59:09.725109
10131   3060 days 13:31:09.725109
10132   3026 days 18:48:09.725109
10133   2983 days 02:34:09.725109
Name: fecha_envio_limite, Length: 10111, dtype: timedelta64[ns]