In [1]:
import os
import pandas as pd
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [3]:
data= pd.read_csv('Ordenes_productos_C1_M2.csv', sep=';',encoding='latin-1')

In [4]:
data.head(5)

,orden_id,order_item_id,producto_id,vendedor_id,fecha_envio_limite,precio,valor_flete,codigo_postal_vendedor,ciudad_vendedor,departamento_vendedor,nombre_categoria_producto,longitud_nombre_producto,longitud_descripcion_producto,cantidad_fotos_producto,peso_g_producto,longitud_cm_producto,altura_cm_producto,ancho_cm_producto
0,107500PO59A,A,PO59,VE5389,07/04/2018 18:12,271.86,30.72,52435,Mallama,Nariño,Productos ecoamigables,6,7,27,2486,17,11,14
1,37493PS22B,B,PS22,VE1558,20/10/2017 09:07,115.73,4.68,52203,Colon,Nariño,Carnicería,10,31,20,256,43,2,21
2,28050PK20B,B,PK20,VE9159,17/08/2017 08:15,432.99,82.70,66001,Pereira,Risaralda,Deportes,25,5,4,5270,9,27,29
3,52187PA10A,A,PA10,VE3159,23/09/2017 23:27,108.38,35.39,52435,Mallama,Nariño,Electrodomésticos,10,1,6,734,46,48,22
4,84639PR12A,A,PR12,VE5090,07/01/2018 11:50,51.50,11.10,73001,Ibague,Tolima,Frutas y verduras,23,16,35,884,45,26,18

In [5]:
#buscar los top 5  categorías de productos 
categoria_top=data.groupby('nombre_categoria_producto').count().reset_index()[['nombre_categoria_producto','producto_id']].sort_values(by=['producto_id'], ascending=False)
categoria_top_lista=categoria_top.head()['nombre_categoria_producto']
categoria_top.head()

   nombre_categoria_producto  producto_id
19                Tecnología          543
3                   Deportes          537
7          Frutas y verduras          532
1                 Carnicería          523
15           Ropa de adultos          521

In [6]:
# Encontrar los departamentos top 5
departamento_top=data.groupby('departamento_vendedor').count().reset_index()[['departamento_vendedor','producto_id']].sort_values(by=['producto_id'], ascending=False)
departamento_top_lista=departamento_top.head()['departamento_vendedor'].to_list()
departamento_top.head()

   departamento_vendedor  producto_id
21                Nariño         3648
20                  Meta         1258
22    Norte de santander          473
25             Risaralda          405
7                 Caldas          378

In [7]:
#filtrar por los departamentos top
data_top=data[data['nombre_categoria_producto'].isin(categoria_top_lista) & data['departamento_vendedor'].isin(departamento_top_lista)]
data_top.head()

,orden_id,order_item_id,producto_id,vendedor_id,fecha_envio_limite,precio,valor_flete,codigo_postal_vendedor,ciudad_vendedor,departamento_vendedor,nombre_categoria_producto,longitud_nombre_producto,longitud_descripcion_producto,cantidad_fotos_producto,peso_g_producto,longitud_cm_producto,altura_cm_producto,ancho_cm_producto
1,37493PS22B,B,PS22,VE1558,20/10/2017 09:07,115.73,4.68,52203,Colon,Nariño,Carnicería,10,31,20,256,43,2,21
2,28050PK20B,B,PK20,VE9159,17/08/2017 08:15,432.99,82.70,66001,Pereira,Risaralda,Deportes,25,5,4,5270,9,27,29
5,73003PS37A,A,PS37,VE3806,09/12/2017 16:52,132.51,33.68,52356,Ipiales,Nariño,Carnicería,13,19,29,811,29,9,16
6,41673PB76A,A,PB76,VE2456,11/02/2018 20:04,420.95,12.19,52240,Chachagui,Nariño,Ropa de adultos,8,37,24,621,26,41,29
8,6725PK32A,A,PK32,VE8613,30/01/2018 17:32,113.54,4.48,52381,La florida,Nariño,Deportes,7,11,30,30,50,26,17

In [21]:
#realizar la tabla de contingencia
tabla_contingencia=pd.crosstab(data_top['nombre_categoria_producto'],data['departamento_vendedor'],margins = True)
tabla_contingencia

departamento_vendedor,Caldas,Meta,Nariño,Norte de santander,Risaralda,All
nombre_categoria_producto,,,,,,
Carnicería,19,65,188,24,19,315
Deportes,21,75,209,20,14,339
Frutas y verduras,25,71,189,28,20,333
Ropa de adultos,12,66,205,28,19,330
Tecnología,21,63,196,27,19,326
All,98,340,987,127,91,1643

In [9]:
pd.crosstab(data_top['nombre_categoria_producto'],data['departamento_vendedor'],margins = True, normalize='index')

departamento_vendedor,Caldas,Meta,Nariño,Norte de santander,Risaralda
nombre_categoria_producto,,,,,
Carnicería,0.060317,0.206349,0.596825,0.076190,0.060317
Deportes,0.061947,0.221239,0.616519,0.058997,0.041298
Frutas y verduras,0.075075,0.213213,0.567568,0.084084,0.060060
Ropa de adultos,0.036364,0.200000,0.621212,0.084848,0.057576
Tecnología,0.064417,0.193252,0.601227,0.082822,0.058282
All,0.059647,0.206939,0.600730,0.077298,0.055386

In [12]:
pd.crosstab(data_top['nombre_categoria_producto'],data['departamento_vendedor'],margins = True, normalize='columns')

departamento_vendedor,Caldas,Meta,Nariño,Norte de santander,Risaralda,All
nombre_categoria_producto,,,,,,
Carnicería,0.186275,0.198113,0.193515,0.181818,0.108333,0.186699
Deportes,0.215686,0.188679,0.201883,0.146853,0.208333,0.195851
Frutas y verduras,0.176471,0.182390,0.200837,0.300699,0.266667,0.209274
Ropa de adultos,0.166667,0.207547,0.192469,0.153846,0.266667,0.195851
Tecnología,0.254902,0.223270,0.211297,0.216783,0.150000,0.212325

In [17]:
# tabla de contingencia con porcentajes
pd.crosstab(data_top['nombre_categoria_producto'],data['departamento_vendedor'],margins = True, normalize='all')

departamento_vendedor,Caldas,Meta,Nariño,Norte de santander,Risaralda,All
nombre_categoria_producto,,,,,,
Carnicería,0.011564,0.039562,0.114425,0.014607,0.011564,0.191722
Deportes,0.012781,0.045648,0.127206,0.012173,0.008521,0.206330
Frutas y verduras,0.015216,0.043214,0.115033,0.017042,0.012173,0.202678
Ropa de adultos,0.007304,0.040170,0.124772,0.017042,0.011564,0.200852
Tecnología,0.012781,0.038344,0.119294,0.016433,0.011564,0.198418
All,0.059647,0.206939,0.600730,0.077298,0.055386,1.000000

In [11]:
tabla_contingencia

departamento_vendedor,Caldas,Meta,Nariño,Norte de santander,Risaralda,All
nombre_categoria_producto,,,,,,
Carnicería,19,65,188,24,19,315
Deportes,21,75,209,20,14,339
Frutas y verduras,25,71,189,28,20,333
Ropa de adultos,12,66,205,28,19,330
Tecnología,21,63,196,27,19,326
All,98,340,987,127,91,1643

In [22]:
#utilizar el mínimo para columnas
tabla_contingencia.min()

departamento_vendedor
Caldas                 12
Meta                   63
Nariño                188
Norte de santander     20
Risaralda              14
All                   315
dtype: int64

In [23]:
#utilizar el mínimo para filas
tabla_contingencia.transpose().min()

nombre_categoria_producto
Carnicería           19
Deportes             14
Frutas y verduras    20
Ropa de adultos      12
Tecnología           19
All                  91
dtype: int64

In [17]:
#Establecer los valores del test chi cuadrado
chi, pval, dof, exp = chi2_contingency(tabla_contingencia)

print('p-valor es: ', pval)

significancia = 0.05
p = 1 - significancia

valor_critico = chi2.ppf(p, dof)
print('chi=%.6f, valor crítico=%.6f\n' % (chi, valor_critico))

if chi > valor_critico:
    print("""A un %.2f de nivel de significancia, se rechaza la hipótesis nula y se acepta H1. 
No son independientes, por lo tanto están correlacionados""" % (significancia))
else:
    print("""A un %.2f de nivel de significancia, no se rechaza la hipótesis nula. 
Son independientes, no tienen relación""" % (significancia))

p-valor es:  0.48301469357016336
chi=24.634237, valor crítico=37.652484

A un 0.05 de nivel de significancia, no se rechaza la hipótesis nula.
Son independientes, no tienen relación